version: '3.3'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: changeme
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    volumes: 
      - ./0-upload_large_dumps.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini
    ports:
      - 8082:8080
volumes:
  db_data: {}